{autoload_i18n}
<form id="forms_catalog_plugin_soundcloud_add" class="form-inline" method="post" action="">
    <p class="control-group">
        <label for="url_media_sc">URL :</label>
        <input type="text" class="input-xxlarge" id="url_media_sc" name="url_media_sc" value="" size="50" />
        <button type="submit" class="btn btn-primary">{#send#|ucfirst}</button>
    </p>
</form>
<div id="list-soundcloud"></div>