<form id="forms_plugins_soundcloud_add" method="post" action="">
    <p class="control-group">
        <label for="name_sc_h">Nom :</label>
        <input type="text" class="input-xlarge" id="name_sc_h" name="name_sc_h" value="" size="50" />
    </p>
    <p class="control-group">
        <label for="url_media_sc_h">URL :</label>
        <input type="text" class="input-xlarge" id="url_media_sc_h" name="url_media_sc_h" value="" size="50" />
    </p>
</form>